title: Lee Woongkyu
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Lee Woongkyu
avatar: /logo.png
email: lwggogl@gmail.com

remote_theme : ngzhio/jekyll-theme-hamilton
url : "https://leewoongkyu.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl : "" # the subpath of your site, e.g. "/blog"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================

# twitter:
  # username: ngzhio
  # card: summary


logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/ngzhio
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
